### ISSUE TITLE
[Interop] Prefixed properties

### ISSUE THREAD

**Issue by llemeurfr** [w3c/publ-cg#23]
Please consult https://github.com/readium/readium-css/issues/32, which has the same title (we'll keep it to summarize the conclusion of this thread in the scope of Readium CSS). 

The crux of the issue is that distributors shouldn't ask EPUB authors to harm interoperability by asking constrained EPUB implementations. It this case, the issue is about prefixed properties (e.g. those required for handling vertical writing). But it could be in other domains of CSS, or why not HTML5. 
 
We think that such issue must be escalated to the EPUB 3 CG, acting as a "WHATWG-style" forum for enhancing the interoperability of reading systems. What should the CG do for such issues? can it act as a hub where authors, distributors/booksellers (Google in this case) and reading system developers can settle on good practices? 

Related threads: 
https://github.com/readium/readium-css/issues/19 
https://github.com/readium/readium-css/issues/26

**Comment by GarthConboy** [comment]
And, FWIW, I added an issue the [readium/readium-css/32](https://github.com/readium/readium-css/issues/32) -- there should be no such issue.

**Comment by llemeurfr** [comment]
Thanks @GarthConboy, it means that this CG can indeed act as a forum for resolving EPUB interop issues, which is great!

**Comment by llemeurfr** [comment]
This issue can now be closed, as it'll soon be resolved by the distributor.
