### ISSUE TITLE
Bad redirects from IDPF a11y guidelines site

### ISSUE THREAD

**Issue by dauwhe** [w3c/publ-cg#60]
https://idpf.github.io/a11y-guidelines/content/nav/pagelist.html

redirects to 

http://www.idpf.org/accessibility/redirect.html

Which is a less-than-ideal user experience. If the repo was unarchived, could we at least redirect some of the pages to their DAISY KB equivalents? In the example above, that would be http://kb.daisy.org/publishing/docs/navigation/pagelist.html

**Comment by TzviyaSiegman** [comment]
What about a banner at the top of the old site with a warning, something like "This is dated material. Go to the daisy KB for more up to date information."

**Comment by mattgarrish** [comment]
That was my first suggestion about a year ago... worry was that people would just ignore the message.

I've modified the initial redirects to pass the kb-equivalent page through as a parameter (or the index page if there isn't (yet) an equivalent). This gets picked up by the redirect page now and there will be a message that you'll be redirected on.

**Comment by dauwhe** [comment]
The redirect works!
