### ISSUE TITLE
Do something with Schema Integration Guide

### ISSUE THREAD

**Issue by dauwhe** [w3c/publ-cg#7]
It turns out we have a guide to using schema.org with EPUB: https://idpf.github.io/epub-guides/schema-org-integration/

Let's not forget this! I'll try to move it to one of the CG repos at some point. Looks like it will need updating due to @refines anyway...

**Comment by mattgarrish** [comment]
Might be a good idea to just transfer the whole guides repository. There are others in there that are going to be useful in the future.

Many (most? all?) are referenced from specs, too, so if we start moving we also need to be careful about breaking links.

There's a comprehensive list of everything we published in IDPF here: http://www.idpf.org/epub/dir/

**Comment by dauwhe** [comment]
I've started migrating some, and cleaning up some of the [expletive deleted] Google Docs HTML. A work in progress...

**Comment by clapierre** [comment]
I have been updating this wikipage on accessibility 1.0 specific schema.org metadata properties recently added, there is still more work which I will do soon.  
https://www.w3.org/wiki/WebSchemas/Accessibility

**Comment by dauwhe** [comment]
Closing as we do have a version of this in this repo: https://w3c.github.io/publ-cg/guides/schema-org-integration.html
