### ISSUE TITLE
Linking to EPUBs without annoying retailers

### ISSUE THREAD

**Issue by dauwhe** [w3c/publ-cg#78]
We often want to link to other books by the same author, or related works. But retailers don't want us to link to other bookstores. How can we craft links that will resolve to a given book on a given platform? Can decentralized identifiers help? Could such an identifier resolve differently depending on the environment?

**Comment by TzviyaSiegman** [comment]
to keep in mind for future: The [Decentralized Identifier](https://w3c-ccg.github.io/did-spec/) draft spec

**Comment by laudrain** [comment]
For other books from same author, the ISNI is a good start to be sure of which "John Smith" is the author.

**Comment by RachelComerford** [comment]
This is out of scope for the EPUB CG to resolve. If it's still of interest, it could be taken to the newly formed Publishing CG for incubation.
