### ISSUE TITLE
Preserving the history of EPUB specifications

### ISSUE THREAD

**Issue by dauwhe** [w3c/publ-cg#79]
http://www.openebook.org/2007/ops/OPS_2.0_final_spec.html gives a 404 error even though the domain redirects to idpf.org

To find anything before 2.0.1 I have to use the wayback machine. Perhaps we should collect old versions of our specs in this repo.

**Comment by mattgarrish** [comment]
They're on the IDPF server:

- http://www.idpf.org/epub/20/spec/OPS_2.0_final_spec.html
- http://www.idpf.org/epub/20/spec/OPF_2.0_final_spec.html

I suspect a blanket redirect was put on openebook.org at some point without concern to whether documents were still hosted in the same locations. I can probably fix that in .htaccess file so the links work again.
