### ISSUE TITLE
Broken images in region-nav-markup

### ISSUE THREAD

**Issue by rakutenjeff** [w3c/publ-cg#86]
https://w3c.github.io/publ-cg/guides/region-nav-markup.html
Looks like image in for example `2.1 panel` is broken.

**Comment by dauwhe** [comment]
Should be fixed by #87. Almost all of the images were missing. 

Note that a lot of the IDs in that doc are bad :(

**Comment by rakutenjeff** [comment]
Thanks @dauwhe !

**Comment by rakutenjeff** [comment]
Lol, yes might need to fix that doc as well.
