### ISSUE TITLE
epub micropayment monetization

### ISSUE THREAD

**Issue by topshef** [w3c/publ-cg#99]
Are there, or have there been, any projects to incorporate streaming payment into the epub format?

The epub file would be encrypted and the book would only be viewable if a valid payment method were plugged into the reader.

Any thoughts, suggestions, leads, obstacles?

Many thanks
Alex

See also: PPDF portable payable document format:
https://medium.com/@tayloa17/youre-trying-to-read-something-online-but-the-ads-are-blasting-you-like-a-lame-game-of-space-aa48648d31e6

Backlink: https://www.w3.org/community/epub3/

**Comment by dauwhe** [comment]
There are obstacles, but the EPUB format isn't one of them. EPUBs can be encrypted, and then decrypted when a reader makes a payment. But, like everything about presenting EPUBs to end users, this requires some sort of reading system. You could build such a system now, using [Readium LCP](https://readium.org/lcp-specs/) for the encryption and rights management parts, and integrating with web payments.

**Comment by topshef** [comment]
@dauwhe thanks for your quick reply, and the Readium LCP link which is very handy.

Re EPUB encryption,
a) could this be made resistant to piracy? ie impossible for a single fee-payer to generate a decrypted copy
b) could just a part of an EPUB be revealed leaving the rest encrypted (eg to monetize just one chapter)

**Comment by dauwhe** [comment]
> a) could this be made resistant to piracy? ie impossible for a single fee-payer to generate a decrypted copy

Resistant, yes. This is all full-blown standard cryptography. But experience shows that almost every DRM scheme gets cracked eventually...

> b) could just a part of an EPUB be revealed leaving the rest encrypted (eg to monetize just one chapter)

There's no conceptual reason that wouldn't work, but it would likely require a lot of modification to something like LCP.

**Comment by topshef** [comment]
@dauwhe thanks for your input, much appreciated

**Comment by llemeurfr** [comment]
Discussions on DRM are not in the charter of the EPUB WG; you can contact EDRLab to discuss how an LCP solution could be adapted to behave like that.
